variable "cluster_name" {}
variable "pod_identity_assume_role_policy" {}
variable "allow_effect" {}
variable "any_resource" {}
variable "alb_role_name" {}
variable "alb_policy_name" {}
variable "alb_policy_file" {}
variable "alb_namespace" {}
variable "alb_service_account" {}
variable "eso_role_name" {}
variable "eso_policy_name" {}
variable "eso_namespace" {}
variable "eso_service_account" {}
variable "eso_ssm_sid" {}
variable "eso_ssm_actions" {}
variable "eso_ssm_resources" {}
variable "eso_secrets_sid" {}
variable "eso_secrets_actions" {}
variable "eso_secrets_resources" {}
variable "external_dns_role_name" {}
variable "external_dns_policy_name" {}
variable "external_dns_namespace" {}
variable "external_dns_service_account" {}
variable "external_dns_change_sid" {}
variable "external_dns_change_actions" {}
variable "external_dns_change_resources" {}
variable "external_dns_list_sid" {}
variable "external_dns_list_actions" {}
variable "thanos_count" {}
variable "thanos_role_name" {}
variable "thanos_policy_arn" {}
variable "thanos_namespace" {}
variable "thanos_service_accounts" {}
variable "keda_count" {}
variable "keda_role_name" {}
variable "keda_policy_name" {}
variable "keda_namespace" {}
variable "keda_service_account" {}
variable "keda_cloudwatch_sid" {}
variable "keda_cloudwatch_actions" {}
variable "keda_sqs_sid" {}
variable "keda_sqs_actions" {}
variable "keda_sqs_resources" {}
variable "extra_pod_identity_associations" {}
