variable "cidr" {}
variable "pod_secondary_cidr" {}
variable "vpc_tags" {}
variable "internet_gateway_tags" {}
variable "public_subnets" {}
variable "controlplane_subnets" {}
variable "node_subnets" {}
variable "pod_subnets" {}
variable "nat_gateways" {}
variable "public_route_table_tags" {}
variable "private_route_tables" {}
variable "default_route_cidr" {}
variable "s3_endpoint_service_name" {}
variable "s3_endpoint_tags" {}
variable "interface_endpoints" {}
variable "endpoints_security_group_name_prefix" {}
variable "endpoints_security_group_description" {}
variable "endpoints_security_group_tags" {}
variable "endpoints_ingress_cidrs" {}
variable "endpoints_ingress_port" {}
variable "endpoints_ingress_protocol" {}
variable "endpoints_ingress_description" {}
