variable "name" {}
variable "kubernetes_version" {}
variable "controlplane_subnet_ids" {}
variable "node_subnet_ids" {}
variable "endpoint_public_access_cidrs" {}
variable "endpoint_private_access" {}
variable "endpoint_public_access" {}
variable "access_entries" {}
variable "cluster_role_name" {}
variable "cluster_role_policy_arn" {}
variable "cluster_assume_role_policy" {}
variable "cluster_authentication_mode" {}
variable "bootstrap_cluster_creator_admin_permissions" {}
variable "cluster_upgrade_support_type" {}
variable "cluster_create_timeout" {}
variable "cluster_delete_timeout" {}
variable "cluster_log_types" {}
variable "cluster_log_group_count" {}
variable "cluster_log_group_name" {}
variable "log_retention_days" {}
variable "karpenter_discovery_tag_key" {}
variable "karpenter_discovery_tag_value" {}
variable "node_role_name" {}
variable "node_assume_role_policy" {}
variable "node_role_policy_arns" {}
variable "system_node_group_name" {}
variable "system_ami_type" {}
variable "system_kubernetes_version" {}
variable "system_release_version" {}
variable "system_update_strategy" {}
variable "system_instance_types" {}
variable "system_capacity_type" {}
variable "system_scaling" {}
variable "system_max_unavailable" {}
variable "system_taint" {}
variable "system_labels" {}
variable "addon_names" {}
variable "addon_versions" {}
variable "addon_resolve_conflicts_on_create" {}
variable "addon_resolve_conflicts_on_update" {}
variable "ebs_csi_configuration_values" {}
variable "pod_identity_assume_role_policy" {}
variable "ebs_csi_role_name" {}
variable "ebs_csi_role_policy_arn" {}
variable "ebs_csi_namespace" {}
variable "ebs_csi_service_account" {}
variable "allow_effect" {}
variable "service_principal_type" {}
variable "any_resource" {}
variable "karpenter_node_role_name" {}
variable "karpenter_node_access_entry_type" {}
variable "karpenter_queue_name" {}
variable "karpenter_queue_retention_seconds" {}
variable "karpenter_queue_sse_enabled" {}
variable "karpenter_queue_policy_sid" {}
variable "karpenter_queue_policy_actions" {}
variable "karpenter_queue_policy_principals" {}
variable "karpenter_event_rules" {}
variable "karpenter_controller_role_name" {}
variable "karpenter_controller_policy_name" {}
variable "karpenter_namespace" {}
variable "karpenter_service_account" {}
variable "karpenter_compute_sid" {}
variable "karpenter_compute_actions" {}
variable "karpenter_pricing_sid" {}
variable "karpenter_pricing_actions" {}
variable "karpenter_interruption_sid" {}
variable "karpenter_interruption_actions" {}
variable "karpenter_pass_node_role_sid" {}
variable "karpenter_pass_node_role_actions" {}
variable "karpenter_instance_profile_sid" {}
variable "karpenter_instance_profile_actions" {}
variable "karpenter_eks_sid" {}
variable "karpenter_eks_actions" {}
variable "karpenter_ssm_sid" {}
variable "karpenter_ssm_actions" {}
variable "karpenter_ssm_resources" {}
