variable "region" {}
variable "resource_prefix" {}
variable "account_id" {}
variable "default_tags" {}
variable "state_bucket_basename" {}
variable "state_sse_algorithm" {}
variable "state_noncurrent_expiration_days" {}
variable "break_glass_principals" {}
variable "github_repos" {}
variable "github_oidc_url" {}
variable "github_oidc_client_ids" {}
variable "github_oidc_thumbprints" {}
variable "gha_role_basename" {}
variable "gha_role_policy_arn" {}
variable "gha_max_session_duration" {}
variable "state_versioning_status" {}
variable "state_bucket_key_enabled" {}
variable "state_block_public_access" {}
variable "state_expire_rule_id" {}
variable "state_expire_rule_status" {}
