apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # external-secrets(컨트롤러) 설치 후 — CRD 필요
spec:
  project: hub
  source:
    repoURL: git@github.com:your-org/eks-hub-spoke-gitops.git
    path: platform/hub/eso
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
