apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-node-pool
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: hub
  source:
    repoURL: git@github.com:your-org/eks-hub-spoke-gitops.git
    path: platform/hub/karpenter/node-pool
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
