apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storageclass
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: hub
  source:
    repoURL: git@github.com:your-org/eks-hub-spoke-gitops.git
    path: platform/hub/storageclass
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
