variable "access_entries" {}
variable "access_scope_namespace" {}
variable "account_id" {}
variable "addon_names" {}
variable "addon_resolve_conflicts" {}
variable "addon_versions" {}
variable "alb_namespace" {}
variable "alb_policy_file" {}
variable "alb_policy_name" {}
variable "alb_service_account" {}
variable "allow_effect" {}
variable "any_resource" {}
variable "api_ingress_description" {}
variable "api_ingress_port" {}
variable "aws_principal_type" {}
variable "bootstrap_cluster_creator_admin_permissions" {}
variable "cluster_authentication_mode" {}
variable "cluster_create_timeout" {}
variable "cluster_delete_timeout" {}
variable "cluster_log_types" {}
variable "cluster_name_base" {}
variable "cluster_role_managed_policy" {}
variable "cluster_upgrade_support_type" {}
variable "default_tags" {}
variable "dns_ssm_namespace" {}
variable "dns_zone_id_key" {}
variable "ebs_csi_controller_toleration" {}
variable "ebs_csi_managed_policy" {}
variable "ebs_csi_namespace" {}
variable "ebs_csi_service_account" {}
variable "eks_ssm_namespace" {}
variable "endpoint_private_access" {}
variable "endpoint_public_access" {}
variable "endpoint_public_access_cidrs" {}
variable "eso_namespace" {}
variable "eso_policy_name" {}
variable "eso_secrets_actions" {}
variable "eso_secrets_sid" {}
variable "eso_service_account" {}
variable "eso_ssm_actions" {}
variable "eso_ssm_sid" {}
variable "external_dns_change_actions" {}
variable "external_dns_change_sid" {}
variable "external_dns_list_actions" {}
variable "external_dns_list_sid" {}
variable "external_dns_namespace" {}
variable "external_dns_policy_name" {}
variable "external_dns_service_account" {}
variable "extra_pod_identity_associations" {}
variable "hub_account_id" {}
variable "hub_cluster_name_base" {}
variable "hub_cluster_sg_id_key" {}
variable "hub_management_role_suffix" {}
variable "karpenter_compute_actions" {}
variable "karpenter_compute_sid" {}
variable "karpenter_controller_policy_name" {}
variable "karpenter_discovery_tag_key" {}
variable "karpenter_eks_actions" {}
variable "karpenter_eks_sid" {}
variable "karpenter_events" {}
variable "karpenter_instance_profile_actions" {}
variable "karpenter_instance_profile_sid" {}
variable "karpenter_interruption_actions" {}
variable "karpenter_interruption_sid" {}
variable "karpenter_namespace" {}
variable "karpenter_node_access_entry_type" {}
variable "karpenter_pass_node_role_actions" {}
variable "karpenter_pass_node_role_sid" {}
variable "karpenter_pricing_actions" {}
variable "karpenter_pricing_sid" {}
variable "karpenter_queue_policy_actions" {}
variable "karpenter_queue_policy_principals" {}
variable "karpenter_queue_policy_sid" {}
variable "karpenter_queue_retention_seconds" {}
variable "karpenter_queue_sse_enabled" {}
variable "karpenter_service_account" {}
variable "karpenter_ssm_actions" {}
variable "karpenter_ssm_sid" {}
variable "keda_cloudwatch_actions" {}
variable "keda_cloudwatch_sid" {}
variable "keda_count" {}
variable "keda_namespace" {}
variable "keda_policy_name" {}
variable "keda_service_account" {}
variable "keda_sqs_actions" {}
variable "keda_sqs_sid" {}
variable "kubernetes_version" {}
variable "log_retention_days" {}
variable "node_managed_policies" {}
variable "observability_ssm_namespace" {}
variable "partition" {}
variable "policy_reporter_port" {}
variable "policy_reporter_sg_description" {}
variable "region" {}
variable "resource_prefix" {}
variable "service_principal_type" {}
variable "service_trust_actions" {}
variable "service_trust_principals" {}
variable "sg_protocol" {}
variable "spoke_access_policy_arn" {}
variable "spoke_access_scope_type" {}
variable "spoke_extra_values" {}
variable "spoke_role_suffix" {}
variable "spoke_secret_namespace" {}
variable "spoke_secret_recovery_window_days" {}
variable "spoke_trust_actions" {}
variable "ssm_param_type" {}
variable "system_ami_type" {}
variable "system_capacity_type" {}
variable "system_instance_types" {}
variable "system_kubernetes_version" {}
variable "system_labels" {}
variable "system_max_unavailable" {}
variable "system_node_group_name" {}
variable "system_release_version" {}
variable "system_scaling" {}
variable "system_taint" {}
variable "system_update_strategy" {}
variable "thanos_count" {}
variable "thanos_namespace" {}
variable "thanos_policy_key" {}
variable "thanos_service_accounts" {}
variable "thanos_sidecar_grpc_port" {}
variable "thanos_sidecar_sg_description" {}
variable "vpc_ssm_namespace" {}
