variable "region" {}
variable "resource_prefix" {}
variable "account_id" {}
variable "default_tags" {}
variable "vpc_name_base" {}
variable "vpc_cidr" {}
variable "azs" {}
variable "public_subnet_cidrs" {}
variable "controlplane_subnet_cidrs" {}
variable "node_subnet_cidrs" {}
variable "pod_secondary_cidr" {}
variable "pod_subnet_cidrs" {}
variable "nat_per_az" {}
variable "interface_endpoints" {}
variable "ssm_namespace" {}
variable "default_route_cidr" {}
variable "endpoints_security_group_description" {}
variable "endpoints_ingress_port" {}
variable "endpoints_ingress_protocol" {}
variable "endpoints_ingress_description" {}
variable "ssm_param_type" {}
